version: '3.8'

services:

  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet restore
    volumes:
      - .:/src

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet test
    volumes:
      - .:/src
    depends_on:
      - build

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet build -c release -o /app
    volumes:
      - .:/src
    depends_on:
      - test