@

@host = http://localhost:5255/password-manager/api/credentials
@token = 

###
# @name AddCredential
POST {{host}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "string",
  "email": "user@example.com",
  "password": "string",
  "webSite": "https://github.com/login"
}