@host = http://localhost:5255/password-manager/api/auth

##
# @name Register
POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
  "username": "string",
  "email": "user@example.com",
  "password": "string"
}

##
# @name Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "string"
}